server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: advance-glass-stock
  datasource:
    url: jdbc:h2:file:./data/stockdb;RECOVER=1;AUTO_SERVER=TRUE;
#    url: jdbc:h2:file:./data/stockdb;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_RECONNECT=TRUE
#    url: jdbc:h2:file:./data/stockdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#      ddl-auto: update
#    properties:
#      hibernate:
#        connection:
#          charSet: UTF-8
#        jdbc:
#          time_zone: UTC
    show-sql: true
  h2:
    console:
      enabled: true
#      settings:
#        web-allow-others: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:script/schema.sql
      data-locations: classpath:script/data.sql

#logging:
#  level:
#    org.hibernate.SQL: DEBUG  # ✅ Show only SQL queries
#    org.hibernate.type.descriptor.sql: TRACE  # ✅ Show SQL parameter values
#    org.hibernate.orm.jdbc.bind: TRACE  # ✅ Show SQL binding details
#    org.hibernate.stat: ERROR  # ❌ Prevent logging Hibernate statistics
#    org.hibernate.engine.internal.Cascade: ERROR  # ❌ Prevent recursive cascade logging
#    org.hibernate.pretty: ERROR  # ❌ Disable entity pretty-printing
#    org.hibernate.collection: ERROR  # ❌ Disable collection logging
#    org.hibernate.cache: ERROR  # ❌ Disable cache logging