server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: advance-glass-stock
  datasource:
    url: jdbc:h2:file:./data/stockdb;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE
#    url: jdbc:h2:file:./data/stockdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true